---
title: "Jens Rytter & karin Hald Stay, Madrid Sun 13 - Wed 16 October 2019" 
output: 
  flexdashboard::flex_dashboard:
    theme: sandstone
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load libraries}

library(flexdashboard)
library(dplyr)
library(knitr)
library(kableExtra)
library(plotly)
library(formattable)
library(readxl)
library(DT)
library(lubridate)
library(chron)
library(ggplot2)
library(vistime)
library(scales)
library(tidyverse)

```

DaybyDay {.storyboard}
===================================== 

### _**Day 1- Sunday, October 13th - 2019**_ 


<br><br>

```{r day1 daybyday}

program <- read_excel("program.xlsx", sheet = "day1")
program$finish[is.na(program$finish)] <- ""
program$notes[is.na(program$notes)] <- ""
program$notes[is.na(program$notes)] <- ""

table_style <- function(x){
  x %>% kable(format = "html", escape = F) %>% kable_styling(fixed_thead = T,bootstrap_options = c("striped","condensed","hover","responsive")) %>%
row_spec(0, bold = T, color = "white", background = "black") 
}

program %>% select(1:6) %>% 
  mutate(
  owner = cell_spec(owner,
  "html", color = ifelse(owner == "CEE","#ee7600", "blue"))) %>% table_style()


```


### Day 2- Monday, October 14th - 2019 {data-commentary-width=200}

```{r day2 daybyday}

program <- read_excel("program.xlsx", sheet = "day2")
program$finish[is.na(program$finish)] <- ""
program$notes[is.na(program$notes)] <- ""
program$notes[is.na(program$notes)] <- ""

table_style <- function(x){
  x %>% kable(format = "html", escape = F) %>% kable_styling(fixed_thead = T,bootstrap_options = c("striped","condensed","hover","responsive")) %>%
row_spec(0, bold = T, color = "white", background = "black") 
}

program %>% select(1:6) %>% 
  mutate(
  owner = cell_spec(owner,
  "html", color = ifelse(owner == "CEE","#ee7600", "blue"))) %>% table_style()


```



### Day 3- Tuesday, October 15th - 2019 {data-commentary-width=200}

```{r day3 daybyday}

program <- read_excel("program.xlsx", sheet = "day3")
program$finish[is.na(program$finish)] <- ""
program$notes[is.na(program$notes)] <- ""
program$notes[is.na(program$notes)] <- ""

table_style <- function(x){
  x %>% kable(format = "html", escape = F) %>% kable_styling(fixed_thead = T,bootstrap_options = c("striped","condensed","hover","responsive")) %>%
row_spec(0, bold = T, color = "white", background = "black") 
}

program %>% select(1:6) %>% 
  mutate(
  owner = cell_spec(owner,
  "html", color = ifelse(owner == "CEE","#ee7600", "blue"))) %>% table_style()


```



### Day 4- Wednesday, October 16th - 2019 {data-commentary-width=200}

```{r day4 daybyday}

program <- read_excel("program.xlsx", sheet = "day4")
program$finish[is.na(program$finish)] <- ""
program$notes[is.na(program$notes)] <- ""
program$notes[is.na(program$notes)] <- ""

table_style <- function(x){
  x %>% kable(format = "html", escape = F) %>% kable_styling(fixed_thead = T,bootstrap_options = c("striped","condensed","hover","responsive")) %>%
row_spec(0, bold = T, color = "white", background = "black") 
}

program %>% select(1:6) %>% 
  mutate(
  owner = cell_spec(owner,
  "html", color = ifelse(owner == "CEE","#ee7600", "blue"))) %>% table_style()


```


*** 


Proforma 
===================================== 


_**Jens Rytter & karin Hald Stay**_ {data-width=850}
-------------------------------------------

### Budget as of August 28, 2019

<br>


```{r table}
tables <- function(x){

x %>% select(1:5) %>% mutate(total = paste("EUR", format(round(total, 2L),nsmall = 2,big.mark = ","))) %>% 
  kable(
   format = "html", escape = F) %>% kable_styling(fixed_thead =   T,bootstrap_options = c("striped","condensed","hover","responsive")) %>%
row_spec(0, bold = T, color = "white", background = "black")  %>% 
  column_spec(1, width = "8em") %>% 
  column_spec(5,bold = TRUE, width = "8em")}
```



```{r proforma}

library(DT)
library(readxl)
library(lubridate)
library(dplyr)
library(chron)
library(kableExtra)
library(scales)
library(tidyverse)

proforma <- read_excel("rooming.xlsx", sheet = "prof", range = "C12:H20") 
proforma <- sapply(proforma, as.character)
proforma[is.na(proforma)] <- ""
proforma <- data.frame(proforma, stringsAsFactors = FALSE)
class(proforma$prof_units) <- "numeric"
class(proforma$prof_cost) <- "numeric"
class(proforma$prof_total) <- "numeric"
names(proforma) <- c("date","description","units","unit cost","total","category")


proforma[nrow(proforma),] <- c("","","<strong>Total</strong>","",sum(proforma$total),"")

class(proforma$total) <- "numeric"

tables(proforma)


```

_**Jens Rytter & karin Hald Stay**_ {data-width=150}
-------------------------------------------

<br><br>


### total proforma

```{r proforma_box}

library(dplyr)
library(flexdashboard)

dip <- read_excel("rooming.xlsx", sheet = "dip") 
dip$amount <- as.numeric(dip$amount)
dip_sum <- dip %>% group_by(paid) %>% summarise(sum = sum(amount)) 

total <- sum(dip_sum$sum)

total %>% prettyNum(big.mark = ",") %>% 
valueBox(
         icon = "fa-euro-sign", 
         caption = "Total requested",
         color = "#ffa500")
```


### _**Total paid %**_

```{r diposits_box}

paid_dip <- dip_sum$sum[dip_sum$paid == "yes"] 

gauge(100*paid_dip/total, min = 0, max = 100, symbol = '%', gaugeSectors(colors = "yellow"),label = paste0("Total paid ", paid_dip," "))

```


### _**Summary table %**_

```{r summary}

library(formattable)
library(readxl)

dip <- read_excel("rooming.xlsx", sheet = "dip")
dip$paid <- ifelse(dip$paid == "yes",TRUE,FALSE)
formattable(dip, list(paid = formatter("span",
      style = x ~ style(color = ifelse(x, "green", "red")),
      x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))))
            
```

